version: '3.8'

services:
  influxdb:
    image: influxdb:1.8.10
    networks:
      - k6
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    networks:
      - k6
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_RENDERING_SERVER_URL = http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL = http://grafana:3000/
      - GF_LOG_FILTERS = rendering:debug
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081  

networks:
  k6:
    driver: bridge

volumes:
  influxdb_data:
  grafana_data: